local-repository/struts-2.1.6/src/apps/showcase/src/main/java/org/apache/struts2/showcase/DateAction.java
/*
 * $Id: DateAction.java 476710 2006-11-19 05:05:14Z mrdon $
 *
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.apache.struts2.showcase;

import java.text.DateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;

import com.opensymphony.xwork2.ActionSupport;

/**
 * <code>DateAction</code>
 *
 */
public class DateAction extends ActionSupport {

    private static DateFormat DF = DateFormat.getDateTimeInstance(DateFormat.MEDIUM, DateFormat.MEDIUM);

    private Date now;
    private Date past;
    private Date future;
    private Date after;
    private Date before;


    public String getDate() {
        return DF.format(new Date());
    }


    /**
     * @return Returns the future.
     */
    public Date getFuture() {
        return future;
    }

    /**
     * @return Returns the now.
     */
    public Date getNow() {
        return now;
    }

    /**
     * @return Returns the past.
     */
    public Date getPast() {
        return past;
    }

    /**
     *
     * @return Returns the before date.
     */
    public Date getBefore() {
        return before;
    }

    /**
     *
     * @return Returns the after date.
     */
    public Date getAfter() {
        return after;
    }

    /**
     */
    public String browse() throws Exception {
        Calendar cal = GregorianCalendar.getInstance();
        now = cal.getTime();
        cal.roll(Calendar.DATE, -1);
        cal.roll(Calendar.HOUR, -3);
        past = cal.getTime();
        cal.roll(Calendar.DATE, 2);
        future = cal.getTime();

        cal.roll(Calendar.YEAR, -1);
        before = cal.getTime();

        cal.roll(Calendar.YEAR, 2);
        after = cal.getTime();
        return SUCCESS;
    }

}

local-repository/struts-2.1.6/src/apps/showcase/src/main/java/org/apache/struts2/showcase/DynamicTreeSelectAction.java
/*
 * $Id: DynamicTreeSelectAction.java 528866 2007-04-14 20:19:20Z musachy $
 *
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.apache.struts2.showcase;

import org.apache.struts2.showcase.ajax.tree.Category;

import com.opensymphony.xwork2.ActionSupport;

//START SNIPPET: treeExampleDynamicJavaSelected

public class DynamicTreeSelectAction extends ActionSupport {

    private long nodeId;
    private Category currentCategory;


    public void setNodeId(long nodeId) {
        this.nodeId = nodeId;
    }
    public long getNodeId() {
        return nodeId;
    }


    public String execute() throws Exception {
        currentCategory = Category.getById(nodeId);
        return SUCCESS;
    }


    public String getNodeName() {
        return currentCategory != null ? currentCategory.getName() : "Node not found";
    }
}

//START SNIPPET: treeExampleDynamicJavaSelected

local-repository/struts-2.1.6/src/apps/showcase/src/main/java/org/apache/struts2/showcase/LotsOfOptiontransferselectAction.java
/*
 * $Id: LotsOfOptiontransferselectAction.java 492030 2007-01-03 02:55:43Z ddewolf $
 *
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.apache.struts2.showcase;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.ArrayList;

import com.opensymphony.xwork2.ActionSupport;

/**
 */
public class LotsOfOptiontransferselectAction extends ActionSupport {

    private List _favouriteCartoonCharactersKeys;
    private List _notFavouriteCartoonCharactersKeys;

    private List _favouriteCarsKeys;
    private List _notFavouriteCarsKeys;

    private List _favouriteMotorcyclesKeys;
    private List _notFavouriteMotorcyclesKeys;

    private List _favouriteCountriesKeys;
    private List _notFavouriteCountriesKeys;

    private List _favouriteSportsKeys;
    private List _nonFavouriteSportsKeys;

    private List _favouriteCities;

    private List _prioritisedFavouriteCartoonCharacters;
    private List _prioritisedFavouriteCars;
    private List _prioritisedFavouriteCountries;



    // Cartoon Characters
    public Map getDefaultFavouriteCartoonCharacters() {
        Map m = new LinkedHashMap();
        m.put("heMan", "He-Man");
        m.put("popeye", "Popeye");
        m.put("mockeyMouse", "Mickey Mouse");
        return m;
    }

    public Map getDefaultNotFavouriteCartoonCharacters() {
        Map m = new LinkedHashMap();
        m.put("donaldDuck", "Donald Duck");
        m.put("atomicAnt", "Atomic Ant");
        m.put("pinkPainter", "Pink Painter");
        return m;
    }

    public List getFavouriteCartoonCharacters() {
        return _favouriteCartoonCharactersKeys;
    }

    public void setFavouriteCartoonCharacters(List favouriteCartoonCharacters) {
        _favouriteCartoonCharactersKeys = favouriteCartoonCharacters;
    }

    public List getNotFavouriteCartoonCharacters() {
        return _notFavouriteCartoonCharactersKeys;
    }

    public void setNotFavouriteCartoonCharacters(List notFavouriteCartoonCharacters) {
        _notFavouriteCartoonCharactersKeys = notFavouriteCartoonCharacters;
    }





    // Cars
    public Map getDefaultFavouriteCars() {
        Map m = new LinkedHashMap();
        m.put("alfaRomeo", "Alfa Romeo");
        m.put("Toyota", "Toyota");
        m.put("Mitsubitshi", "Mitsubitshi");
        return m;
    }

    public Map getDefaultNotFavouriteCars() {
        Map m = new LinkedHashMap();
        m.put("ford", "Ford");
        m.put("landRover", "Land Rover");
        m.put("mercedes", "Mercedes");
        return m;
    }

    public List getFavouriteCars() {
        return _favouriteCarsKeys;
    }

    public void setFavouriteCars(List favouriteCars) {
        _favouriteCarsKeys = favouriteCars;
    }

    public List getNotFavouriteCars() {
        return _notFavouriteCarsKeys;
    }

    public void setNotFavouriteCars(List notFavouriteCars) {
        _notFavouriteCarsKeys = notFavouriteCars;
    }



    // Motorcycles
    public Map getDefaultFavouriteMotorcycles() {
        Map m = new LinkedHashMap();
        m.put("honda", "Honda");
        m.put("yamaha", "Yamaha");
        m.put("Aprillia", "Aprillia");
        return m;
    }

    public Map getDefaultNotFavouriteMotorcycles() {
        Map m = new LinkedHashMap();
        m.put("cagiva", "Cagiva");
        m.put("harleyDavidson", "Harley Davidson");
        m.put("suzuki", "Suzuki");
        return m;
    }

    public List getFavouriteMotorcycles() {
        return _favouriteMotorcyclesKeys;
    }

    public void setFavouriteMotorcycles(List favouriteMotorcycles) {
        _favouriteMotorcyclesKeys = favouriteMotorcycles;
    }

    public List getNotFavouriteMotorcycles() {
        return _notFavouriteMotorcyclesKeys;
    }

    public void setNotFavouriteMotorcycles(List notFavouriteMotorcycles) {
        _notFavouriteMotorcyclesKeys = notFavouriteMotorcycles;
    }



    // Countries
    public Map getDefaultFavouriteCountries() {
        Map m = new LinkedHashMap();
        m.put("england", "England");
        m.put("america", "America");
        m.put("brazil", "Brazil");
        return m;
    }

    public Map getDefaultNotFavouriteCountries() {
        Map m = new LinkedHashMap();
        m.put("germany", "Germany");
        m.put("china", "China");
        m.put("russia", "Russia");
        return m;
    }

    public List getFavouriteCountries() {
        return _favouriteCountriesKeys;
    }

    public void setFavouriteCountries(List favouriteCountries) {
        _favouriteCountriesKeys = favouriteCountries;
    }

    public List getNotFavouriteCountries() {
        return _notFavouriteCountriesKeys;
    }

    public void setNotFavouriteCountries(List notFavouriteCountries) {
        _notFavouriteCountriesKeys = notFavouriteCountries;
    }

    // Sports
    public Map getDefaultNonFavoriteSports() {
        Map m = new LinkedHashMap();
        m.put("basketball", "Basketball");
        m.put("football", "Football");
        m.put("baseball", "Baseball");
        return m;
    }

    public Map getDefaultFavoriteSports() {
        return new LinkedHashMap();
    }

    public List getFavouriteSports() {
        return _favouriteSportsKeys;
    }

    public void setFavouriteSports(List favouriteSportsKeys) {
        this._favouriteSportsKeys = favouriteSportsKeys;
    }

    public List getNonFavouriteSports() {
        return _nonFavouriteSportsKeys;
    }

    public void setNonFavouriteSports(List notFavouriteSportsKeys) {
        this._nonFavouriteSportsKeys = notFavouriteSportsKeys;
    }


    

    public List getPrioritisedFavouriteCartoonCharacters() {
        return _prioritisedFavouriteCartoonCharacters;
    }
    public void setPrioritisedFavouriteCartoonCharacters(List prioritisedFavouriteCartoonCharacters) {
        _prioritisedFavouriteCartoonCharacters = prioritisedFavouriteCartoonCharacters;
    }

    public List getPrioritisedFavouriteCars() {
        return _prioritisedFavouriteCars;
    }
    public void setPrioritisedFavouriteCars(List prioritisedFavouriteCars) {
        _prioritisedFavouriteCars = prioritisedFavouriteCars;
    }


    public List getPrioritisedFavouriteCountries() {
        return _prioritisedFavouriteCountries;
    }
    public void setPrioritisedFavouriteCountries(List prioritisedFavouriteCountries) {
        _prioritisedFavouriteCountries = prioritisedFavouriteCountries;
    }



    public Map getAvailableCities() {
        Map map = new LinkedHashMap();
        map.put("boston", "Boston");
        map.put("new york", "New York");
        map.put("london", "London");
        map.put("rome", "Rome");
        return map;
    }

    public List getDefaultFavouriteCities() {
        List list = new ArrayList();
        list.add("boston");
        list.add("rome");
        return list;
    }

    public List getFavouriteCities() {
        return _favouriteCities;
    }

    public void setFavouriteCities(List favouriteCities) {
        this._favouriteCities = favouriteCities;
    }

    // actions

    public String input() throws Exception {
        return SUCCESS;
    }

    public String submit() throws Exception {
        return SUCCESS;
    }
}

local-repository/struts-2.1.6/src/apps/showcase/src/main/java/org/apache/struts2/showcase/LotsOfRichtexteditorAction.java
/*
 * $Id: LotsOfRichtexteditorAction.java 471756 2006-11-06 15:01:43Z husted $
 *
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.apache.struts2.showcase;

import com.opensymphony.xwork2.ActionSupport;

/**
 *
 */
public class LotsOfRichtexteditorAction extends ActionSupport {

    public String description1;
    public String description2 = "This is Description 2";
    public String description3;
    public String description4 = "This is Description 4";

    public String getDescription1() {
        return this.description1;
    }
    public void setDescription1(String description1) {
        this.description1 = description1;
    }


    public String getDescription2() {
        return this.description2;
    }
    public void setDescription2(String description2) {
        this.description2 = description2;
    }


    public String getDescription3() {
        return this.description3;
    }
    public void setDescription3(String description3) {
        this.description3 = description3;
    }




    public String getDescription4() {
        return this.description4;
    }
    public void setDescription4(String description4) {
        this.description4 = description4;
    }




    public String input() throws Exception {
        return SUCCESS;
    }

    public String submit() throws Exception {
        return SUCCESS;
    }
}

local-repository/struts-2.1.6/src/apps/showcase/src/main/java/org/apache/struts2/showcase/ShowAjaxDynamicTreeAction.java
/*
 * $Id: ShowAjaxDynamicTreeAction.java 590812 2007-10-31 20:32:54Z apetrelli $
 *
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.apache.struts2.showcase;

import org.apache.struts2.showcase.ajax.tree.Category;

import com.opensymphony.xwork2.ActionSupport;

public class ShowAjaxDynamicTreeAction extends ActionSupport {
    private int nodeId = 1;

    public Category getCategory() {
        return Category.getById(nodeId);
    }

    public int getNodeId() {
        return nodeId;
    }

    public void setNodeId(int nodeId) {
        this.nodeId = nodeId;
    }
}

local-repository/struts-2.1.6/src/apps/showcase/src/main/java/org/apache/struts2/showcase/ajax/AjaxTestAction.java
/*
 * $Id: AjaxTestAction.java 483215 2006-12-06 20:40:24Z hermanns $
 *
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.apache.struts2.showcase.ajax;

import com.opensymphony.xwork2.Action;

import java.io.Serializable;


/**
 */
public class AjaxTestAction implements Action, Serializable {

    private static int counter = 0;
    private String data;

    public long getServerTime() {
        return System.currentTimeMillis();
    }

    public int getCount() {
        return ++counter;
    }

    public String getData() {
        return data;
    }

    public void setData(String data) {
        this.data = data;
    }

    public String execute() throws Exception {
        return SUCCESS;
    }
}

local-repository/struts-2.1.6/src/apps/showcase/src/main/webapp/date.jsp
<%@ taglib prefix="s" uri="/struts-tags" %>
<s:date name="now"/>

local-repository/struts-2.1.6/src/apps/showcase/src/main/webapp/help.jsp
<%@taglib prefix="s" uri="/struts-tags" %>
<html>
<head>
    <title>Struts ~ Getting Support</title>
</head>

<body>
    <div id="main">
        <h4>Getting support</h4>

        <table style="width: auto;">
            <tr>
                <th style="width: auto;">Link</th>
                <th style="width: auto;">Description</th>
            </tr>
            <tr>
                <td><a href="http://struts.apache.org/mail.html">User List</a></td>
                <td>Use this mailing list if you encounter problems while developing and using with Struts</td>
            </tr>
            <tr>
                <td><a href="http://struts.apache.org/2.x/">Struts 2</a></td>
                <td>The Struts 2 website</td>
            </tr>
        </table>
    </div>

    <div id="local">
        <img src='<s:url value="/images/struts.gif"/>' alt="Struts Logo" width="290" height="80"/>
    </div>
</body>
</html>

local-repository/struts-2.1.6/src/apps/showcase/src/main/webapp/index.jsp
<% response.sendRedirect("showcase.action"); %>

local-repository/struts-2.1.6/src/apps/showcase/src/main/webapp/showcase.jsp
<%-- 
    showcase.jsp
    
    @version $Date: 2007-08-21 23:07:00 +0000 (Tue, 21 Aug 2007) $ $Id: showcase.jsp 568318 2007-08-21 23:07:00Z musachy $
--%>

<%@ taglib prefix="s" uri="/struts-tags" %>
<html>
<head>
    <title>Showcase</title>
    <s:head theme="simple"/>
</head>

<body>
    <blockquote>
        <p>
            The Struts Showcase demonstrates a variety of use cases and tag usages.
            Essentially, the application exercises various framework features in isolation.
            <em>The Showcase is <strong>not</strong> meant as a "best practices" example.</em>
        </p>
        <ul>
            <li>
                For more "by example" solutions,
                see the <a href="http://struts.apache.org/2.x/docs/cookbook.html">Struts Cookbook</a> pages.
            </li>
            <li>
                For a "best practices" example, see the
                <a href="http://planetstruts.org/struts2-mailreader/">MailReader application</a> Tour and source code.
            </li>
        </ul>
    </blockquote>
    <p>
    <%-- THIS LIST IS MAINTAINED IN WEB-INF/decorators/main.jsp TO CREATE THE MENU BAR -- EDIT THERE AND COPY HERE --%>
    <ul>
        <li><a href="<s:url value="/showcase.jsp"/>">Home</a></li>        
        <li><a href="<s:url value="/interactive/index.jsp" />">Interactive demo of OGNL and JSP tags</a></li>   
        <li><a href="<s:url value="/ajax/index.jsp" />">Ajax plugin for Struts</a></li>
        <li><a href="<s:url value="/chat/index.jsp"/>">Ajax Chat</a>
        <li><a href="<s:url action="actionChain1!input" namespace="/actionchaining"  includeParams="none" />">Action Chaining</a></li>
        <li><a href="<s:url action="index" namespace="/config-browser" includeParams="none" />">Config Browser</a></li>
        <li><a href="<s:url value="/conversion/index.jsp"/>">Conversion</a></li>
        <li><a href="<s:url value="/empmanager/index.jsp"/>">CRUD</a></li>
        <li><a href="<s:url value="/wait/index.jsp"/>">Execute & Wait</a></li>
        <li><a href="<s:url value="/filedownload/index.jsp"/>">File Download</a></li>
        <li><a href="<s:url value="/fileupload/index.jsp" />">File Upload</a></li>
        <li><a href="<s:url value="/freemarker/index.jsp"/>">Freemarker</a>
        <li><a href="<s:url action="hangmanMenu" namespace="/hangman"/>">Hangman</a></li>
        <li><a href="<s:url value="/jsf/index.jsp"/>">JavaServer Faces</a></li>
        <li><a href="<s:url value="/person/index.jsp"/>">Person Manager</a></li>
        <li><a href="<s:url value="/tags/index.jsp"/>">Tags</a></li>
        <li><a href="<s:url value="/tiles/index.action" />">Tiles</a></li>
        <li><a href="<s:url value="/token/index.jsp"/>">Token</a></li>
        <li><a href="<s:url value="/validation/index.jsp"/>">Validation</a></li>
        <li class="last"><a href="<s:url value="/help.jsp"/>">Help</a></li>
     </ul>

    <h2>Sandbox</h2>
    <p>
        These examples are under development and may not be fully operational.
    </p>
    <ul>
        <li><a href="<s:url action="guess" namespace="/continuations" />">Continuations</a></li>
    </ul>

</p>

</body>
</html>

local-repository/struts-2.1.6/src/apps/showcase/src/main/webapp/viewSource.jsp
<%@ taglib prefix="s" uri="/struts-tags" %>
<%@ taglib prefix="sx" uri="/struts-dojo-tags" %>
<html>
<head>
    <title>View Sources</title>

    <jsp:include page="/ajax/commonInclude.jsp"/>
</head>
<body>
<h1>View Sources</h1>

<sx:tabbedpanel id="test">
	<sx:div id="one" label="Page" >
        <h3>${empty page ? "Unknown page" : page}</h3>
<pre>
<s:iterator value="pageLines" status="row">
${row.count}: <s:property/></s:iterator>
</pre>
    </sx:div>
    <sx:div id="two" label="Configuration" >
        <h3>${empty config ? "Unknown configuration" : config}</h3>
<pre>

<s:iterator value="configLines" status="row"><s:if test="%{(#row.count-1)==(configLines.size()/2)}">
<span style="background-color:yellow">${configLine - padding + row.count - 1}: <s:property/></span></s:if><s:else>
${configLine - padding + row.count - 1}: <s:property/></s:else></s:iterator>
</pre>
    </sx:div>
    <sx:div id="three" label="Java Action">
        <h3>${empty className ? "Unknown or unavailable Action class" : className}</h3>
<pre>
<s:iterator value="classLines" status="row">
${row.count}: <s:property/></s:iterator>
</pre>
    </sx:div>
    
</sx:tabbedpanel>

</body>
</html>